version: '2'
 services:
   web:
     container_name: bitcoin-resin
     build: .
     ports:
      - "80:80"
     depends_on:
      - redis
   redis:
     container_name: redis_store
     image: armhf/redis